// Generated by scripts/print-cards.cjs from the files in art/. Do not edit by hand.
import type { HouseId } from './engine/types';

export const CARD_PICTURES: Record<number, string> = {};
export const PORTRAIT_FILES: Partial<Record<HouseId, (string | undefined)[]>> = {};
export const CREST_FILES: Partial<Record<HouseId, string>> = {};
