// Generated by scripts/print-cards.cjs from the files in art/. Do not edit by hand.
import type { HouseId } from './engine/types';

export const CARD_PICTURES: Record<number, string> = {
  "1": "/art/cards/card-1.webp",
  "2": "/art/cards/card-2.webp",
  "3": "/art/cards/card-3.webp",
  "4": "/art/cards/card-4.webp",
  "5": "/art/cards/card-5.webp",
  "6": "/art/cards/card-6.webp",
  "7": "/art/cards/card-7.webp",
  "8": "/art/cards/card-8.webp",
  "9": "/art/cards/card-9.webp",
  "10": "/art/cards/card-10.webp",
  "11": "/art/cards/card-11.webp",
  "12": "/art/cards/card-12.webp",
  "13": "/art/cards/card-13.webp",
  "14": "/art/cards/card-14.webp",
  "15": "/art/cards/card-15.webp",
  "16": "/art/cards/card-16.webp",
  "17": "/art/cards/card-17.webp",
  "18": "/art/cards/card-18.webp",
  "19": "/art/cards/card-19.webp",
  "20": "/art/cards/card-20.webp"
};
export const PORTRAIT_FILES: Partial<Record<HouseId, (string | undefined)[]>> = {};
export const CREST_FILES: Partial<Record<HouseId, string>> = {};
